### ISSUE TITLE
Demo video

### ISSUE THREAD

**Issue by HabibSlim** [threedle/GeoCode#16]
Hello. Thanks for your work, it is a great resource and I'm exploring ways to use it atm.

This is not directly related to GeoCode, but how did you render the demo video?
I loved the morphing effects between shapes and the different effects but I have 0 clue how you did it (does Blender support morphing animations?)

Thanks in advance 👯‍♂️

**Comment by ofekp** [comment]
ofc Blender can do morphing, but you don't need to worry about that because all the morphing is done by GeoCode's shape programs. If you change any continuous parameter gradually the shape will change gradually into another shape variation, depending on what parameter you changed.
Basically, open Blender's animation workspace, add a keyframe to one of the continuous parameters of the shape (e.g. chair shape program), move the animation slider to a different frame, change the same continuous parameter to some other value, and add another keyframe. Press space to see the animation, or create a camera and change the render and output settings to render the scene into a video.

**Comment by HabibSlim** [comment]
Oooh of course, I didn't think about that. Thanks very much for sharing!

The shape programs are very cool by the way, this is a great resource
